### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by mateuszperlak** [maciejtrybula/redirect-service#1]
![image](https://github.com/maciejtrybula/redirect-service/assets/23003982/7eef13ad-7f65-4e73-b20a-e113c328019a)

I have this error on my Netscape browser

**Comment by ikhvost** [comment]
I have the similar issue with images 😔![119482344-0bee4800-bd54-11eb-8bea-9a4a9b30d6b2.png](https://github.com/maciejtrybula/redirect-service/assets/37882343/318ff568-de29-450d-82f5-eed71d20c9f6)

**Comment by maciejtrybula** [comment]
@mrdck @ikhvost 
It was mentioned few times on a forum. Next time please use serach functionality.
I'm closing this issue.
